#2.é…ç½®ç›¸å…³ä¿¡æ¯
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: root

#è®¾ç½®Mpç›¸å…³çš„é…ç½?
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
