# debug: true

logging:
  # è®¾ç½®åˆ†ç»„
  group:
    ebank: com.itheima.controller,com.itheima.service,com.itheima.dao
    iservice: com.alibaba
  level:
    root: info
    # è®¾ç½®æŸä¸ªåŒ…çš„æ—¥å¿—çº§åˆ«
#    com.itheima.controller: debug
    # è®¾ç½®åˆ†ç»„ï¼Œå¯¹æŸä¸ªç»„è®¾ç½®æ—¥å¿—çº§åˆ?
    ebank: warn

  # è®¾ç½®æ—¥å¿—æ¨¡æ¿æ ¼å¼
  pattern:
#    console: "%d - %m %n"
    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log

