# åº”ç”¨ç¯å¢ƒ
# å…¬å…±é…ç½®
spring:
  profiles:
    active: dev
---
# è®¾ç½®ç¯å¢ƒ
# ç”Ÿäº§ç¯å¢ƒ
spring:
  profiles: pro
server:
  port: 80
---
# å¼?å‘ç¯å¢?
spring:
  profiles: dev
server:
  port: 81
---
# æµ‹è¯•ç¯å¢ƒ
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82

